#!/usr/bin/env python3
"""
Database Health Check Script
Auto-generated by RIF-Implementer for Issue #102

Run this script to check database health and diagnose issues.
"""

import sys
import os
from pathlib import Path

# Add RIF modules to path
sys.path.append(str(Path(__file__).parent.parent))

def health_check():
    try:
        from knowledge.database.database_interface import RIFDatabase
        
        with RIFDatabase() as db:
            verification = db.verify_setup()
            stats = db.get_database_stats()
            
            print("Database Health Check Results:")
            print(f"Database Accessible: {'✅' if verification['database_accessible'] else '❌'}")
            print(f"Schema Present: {'✅' if verification['schema_present'] else '❌'}")
            print(f"Connection Pool Working: {'✅' if verification['connection_pool_working'] else '❌'}")
            print(f"Performance Acceptable: {'✅' if verification['performance_acceptable'] else '❌'}")
            print(f"Total Entities: {stats['entities']['total']}")
            print(f"Total Relationships: {stats['relationships']['total']}")
            
            if verification['errors']:
                print("Errors found:")
                for error in verification['errors']:
                    print(f"  ⚠️ {error}")
                    
            return len(verification['errors']) == 0
            
    except Exception as e:
        print(f"❌ Health check failed: {e}")
        return False

if __name__ == "__main__":
    success = health_check()
    sys.exit(0 if success else 1)
