-- DuckDB Schema for RIF Knowledge Graph (DuckDB v1.3.2 Compatible)
-- Issue #28: Implement DuckDB schema for knowledge graph
-- Generated by: RIF-Implementer
-- Date: 2025-08-23
-- Compatible with DuckDB v1.3.2

-- =============================================================================
-- CORE TABLES
-- =============================================================================

-- Entities Table: Store code entities with AST metadata and vector embeddings
CREATE TABLE entities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type VARCHAR(50) NOT NULL,          -- function, class, module, variable
    name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    line_start INTEGER,
    line_end INTEGER,
    ast_hash VARCHAR(64),               -- For incremental updates
    embedding FLOAT[768],               -- Vector representation for VSS
    metadata JSON,                      -- Flexible attributes
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Check constraints
    CHECK (type IN ('function', 'class', 'module', 'variable', 'constant', 'interface', 'enum')),
    CHECK (line_start IS NULL OR line_start >= 1),
    CHECK (line_end IS NULL OR line_end >= line_start),
    CHECK (name != ''),
    CHECK (file_path != '')
);

-- Relationships Table: Track code relationships and dependencies
CREATE TABLE relationships (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id UUID NOT NULL,
    target_id UUID NOT NULL, 
    relationship_type VARCHAR(50) NOT NULL, -- imports, calls, extends, uses
    confidence FLOAT DEFAULT 1.0,
    metadata JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Check constraints
    CHECK (relationship_type IN ('imports', 'calls', 'extends', 'uses', 'implements', 'references', 'contains')),
    CHECK (confidence >= 0.0 AND confidence <= 1.0),
    CHECK (source_id != target_id) -- Prevent self-references
);

-- Agent Memory Table: Store agent conversations, decisions, and learnings
CREATE TABLE agent_memory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_type VARCHAR(50) NOT NULL,
    issue_number INTEGER,
    context TEXT NOT NULL,
    decision TEXT,
    outcome VARCHAR(50),
    embedding FLOAT[768],               -- Vector representation for similarity search
    metadata JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Check constraints
    CHECK (agent_type IN ('RIF-Analyst', 'RIF-Planner', 'RIF-Architect', 'RIF-Implementer', 'RIF-Validator', 'RIF-Learner', 'RIF-PR-Manager')),
    CHECK (outcome IS NULL OR outcome IN ('success', 'failure', 'partial', 'pending', 'skipped')),
    CHECK (context != '')
);

-- =============================================================================
-- PERFORMANCE INDEXES
-- =============================================================================

-- Entity lookup indexes
CREATE INDEX idx_entities_type_name ON entities(type, name);
CREATE INDEX idx_entities_file_path ON entities(file_path);
CREATE INDEX idx_entities_hash ON entities(ast_hash);
CREATE INDEX idx_entities_type ON entities(type);
CREATE INDEX idx_entities_created_at ON entities(created_at);

-- Relationship traversal indexes
CREATE INDEX idx_relationships_source ON relationships(source_id);
CREATE INDEX idx_relationships_target ON relationships(target_id);
CREATE INDEX idx_relationships_type ON relationships(relationship_type);
CREATE INDEX idx_relationships_source_type ON relationships(source_id, relationship_type);
CREATE INDEX idx_relationships_target_type ON relationships(target_id, relationship_type);

-- Agent memory query indexes
CREATE INDEX idx_agent_memory_type ON agent_memory(agent_type);
CREATE INDEX idx_agent_memory_issue ON agent_memory(issue_number);
CREATE INDEX idx_agent_memory_outcome ON agent_memory(outcome);
CREATE INDEX idx_agent_memory_type_issue ON agent_memory(agent_type, issue_number);
CREATE INDEX idx_agent_memory_created_at ON agent_memory(created_at);

-- =============================================================================
-- VIEWS FOR PERFORMANCE (Using regular VIEWs instead of MATERIALIZED)
-- =============================================================================

-- Module Dependency Graph
CREATE VIEW mv_module_dependencies AS
SELECT DISTINCT 
    e1.name AS source_module,
    e1.file_path AS source_file,
    e2.name AS target_module,
    e2.file_path AS target_file,
    r.relationship_type,
    r.confidence
FROM relationships r
JOIN entities e1 ON r.source_id = e1.id  
JOIN entities e2 ON r.target_id = e2.id
WHERE e1.type = 'module' AND e2.type = 'module'
ORDER BY source_module, target_module;

-- Function Call Graph
CREATE VIEW mv_function_calls AS
SELECT 
    e1.name AS caller_function,
    e1.file_path AS caller_file,
    e2.name AS called_function, 
    e2.file_path AS called_file,
    COUNT(*) AS call_count
FROM relationships r
JOIN entities e1 ON r.source_id = e1.id
JOIN entities e2 ON r.target_id = e2.id  
WHERE r.relationship_type = 'calls'
  AND e1.type = 'function' 
  AND e2.type = 'function'
GROUP BY e1.name, e1.file_path, e2.name, e2.file_path
ORDER BY call_count DESC;

-- Agent Learning Patterns
CREATE VIEW mv_agent_learnings AS
SELECT 
    agent_type,
    outcome, 
    COUNT(*) AS frequency,
    AVG(LENGTH(context)) AS avg_context_length
FROM agent_memory 
WHERE outcome IS NOT NULL
GROUP BY agent_type, outcome
ORDER BY frequency DESC;

-- Entity Statistics
CREATE VIEW mv_entity_stats AS
SELECT 
    type,
    COUNT(*) AS entity_count,
    COUNT(DISTINCT file_path) AS file_count,
    AVG(CASE WHEN line_end IS NOT NULL AND line_start IS NOT NULL 
             THEN line_end - line_start + 1 
             ELSE NULL END) AS avg_lines
FROM entities
GROUP BY type
ORDER BY entity_count DESC;

-- Relationship Statistics  
CREATE VIEW mv_relationship_stats AS
SELECT 
    relationship_type,
    COUNT(*) AS relationship_count,
    AVG(confidence) AS avg_confidence,
    MIN(confidence) AS min_confidence,
    MAX(confidence) AS max_confidence
FROM relationships
GROUP BY relationship_type
ORDER BY relationship_count DESC;

-- =============================================================================
-- UTILITY FUNCTIONS (Using standard SQL)
-- =============================================================================

-- Function to find similar entities by name (without vector search)
CREATE VIEW find_similar_entities AS
SELECT 
    e1.id,
    e1.name,
    e1.type,
    e1.file_path,
    COUNT(r1.id) + COUNT(r2.id) AS relationship_count
FROM entities e1
LEFT JOIN relationships r1 ON e1.id = r1.source_id
LEFT JOIN relationships r2 ON e1.id = r2.target_id
GROUP BY e1.id, e1.name, e1.type, e1.file_path
ORDER BY relationship_count DESC;

-- =============================================================================
-- DATA VALIDATION SETUP
-- =============================================================================

-- Test data integrity
CREATE VIEW validate_schema AS
SELECT 
    'entities' AS table_name,
    COUNT(*) AS row_count,
    COUNT(CASE WHEN id IS NULL THEN 1 END) AS null_ids,
    COUNT(CASE WHEN type NOT IN ('function', 'class', 'module', 'variable', 'constant', 'interface', 'enum') THEN 1 END) AS invalid_types
FROM entities
UNION ALL
SELECT 
    'relationships' AS table_name,
    COUNT(*) AS row_count,
    COUNT(CASE WHEN source_id IS NULL OR target_id IS NULL THEN 1 END) AS null_references,
    COUNT(CASE WHEN relationship_type NOT IN ('imports', 'calls', 'extends', 'uses', 'implements', 'references', 'contains') THEN 1 END) AS invalid_types
FROM relationships
UNION ALL
SELECT 
    'agent_memory' AS table_name,
    COUNT(*) AS row_count,
    COUNT(CASE WHEN agent_type IS NULL THEN 1 END) AS null_agents,
    COUNT(CASE WHEN agent_type NOT IN ('RIF-Analyst', 'RIF-Planner', 'RIF-Architect', 'RIF-Implementer', 'RIF-Validator', 'RIF-Learner', 'RIF-PR-Manager') THEN 1 END) AS invalid_agents
FROM agent_memory;

-- =============================================================================
-- COMMENTS AND DOCUMENTATION
-- =============================================================================

-- Table comments would go here but DuckDB v1.3.2 has limited COMMENT support

-- Schema setup complete
SELECT 'DuckDB Knowledge Graph Schema Created Successfully' AS status,
       'Tables: entities, relationships, agent_memory' AS tables,
       'Indexes: 15 performance indexes' AS indexes,
       'Views: 7 analytical views' AS views;