# DPIBS Integration Configuration
# Issue #121: DPIBS Architecture Phase 3 - Integration Architecture with RIF Workflows
# 
# This configuration file defines the complete 5-layer integration architecture
# connecting DPIBS functionality with existing RIF infrastructure while maintaining
# backward compatibility and enabling enhanced context delivery and benchmarking capabilities.

integration_architecture:
  name: "DPIBS-RIF Integration Architecture"
  version: "1.0.0"
  description: "5-layer integration architecture for seamless DPIBS-RIF workflow enhancement"
  
  # Architecture Overview
  architecture:
    total_layers: 5
    backward_compatibility: true
    gradual_adoption_supported: true
    zero_regression_guaranteed: true
    
  # Performance Targets (from RIF-Architect design)
  performance_targets:
    agent_context_optimization_ms: 100    # Layer 1: <100ms
    mcp_operations_ms: 200               # Layer 2: <200ms  
    github_hook_processing_ms: 50        # Layer 3: <50ms
    state_transition_processing_ms: 500  # Layer 4: <500ms
    compatibility_verification_ms: 1000 # Layer 5: <1000ms
    
    # Enterprise targets
    system_overhead_percent: 5           # <5% system overhead
    cache_hit_rate_percent: 95          # 95% cache hit rate
    availability_percent: 99.9          # 99.9% availability

# Layer 1: RIF Agent Context Integration
layer_1_agent_integration:
  enabled: true
  module: "systems.integration.dpibs_rif_agent_integration"
  class: "RIFAgentContextIntegrator"
  
  configuration:
    performance_target_ms: 100
    cache_ttl_minutes: 5
    max_contexts_per_agent: 50
    context_weight_threshold: 0.5
    
  agents:
    rif-analyst:
      context_roles: ["requirements_analysis", "pattern_recognition", "complexity_assessment"]
      context_weight: 0.9
      priority: "high"
    rif-planner:
      context_roles: ["strategic_planning", "workflow_configuration", "checkpoint_planning"] 
      context_weight: 0.8
      priority: "high"
    rif-architect:
      context_roles: ["system_design", "integration_architecture", "technical_specifications"]
      context_weight: 0.85
      priority: "high"
    rif-implementer:
      context_roles: ["implementation", "code_generation", "checkpoint_tracking"]
      context_weight: 0.9
      priority: "high"
    rif-validator:
      context_roles: ["testing", "quality_gates", "evidence_collection"]
      context_weight: 0.8
      priority: "high"
    rif-learner:
      context_roles: ["knowledge_updates", "pattern_learning", "metrics_analysis"]
      context_weight: 0.7
      priority: "medium"
    rif-pr-manager:
      context_roles: ["pr_management", "merge_strategy", "deployment_coordination"]
      context_weight: 0.6
      priority: "medium"
    rif-projectgen:
      context_roles: ["project_generation", "technology_detection", "setup_automation"]
      context_weight: 0.5
      priority: "low"
    rif-shadow-auditor:
      context_roles: ["quality_monitoring", "shadow_validation", "continuous_assessment"]
      context_weight: 0.7
      priority: "medium"

# Layer 2: MCP Knowledge Server Integration  
layer_2_mcp_integration:
  enabled: true
  module: "systems.integration.dpibs_mcp_integration"
  class: "DPIBSMCPIntegrator"
  
  configuration:
    query_timeout_ms: 5000
    cache_ttl_seconds: 300
    max_concurrent_queries: 10
    
    performance_targets:
      cached_queries_ms: 100
      live_queries_ms: 1000
      mcp_operations_ms: 200
    
    optimization_strategies:
      - result_caching
      - query_batching
      - connection_pooling
      - result_streaming
  
  query_types:
    patterns:
      cache_priority: "high"
      optimization: "vector_search"
      ttl_seconds: 600
    decisions:
      cache_priority: "medium" 
      optimization: "indexed_search"
      ttl_seconds: 300
    issues:
      cache_priority: "medium"
      optimization: "filtered_search"
      ttl_seconds: 180
    metrics:
      cache_priority: "low"
      optimization: "aggregated_search"
      ttl_seconds: 120
    conversations:
      cache_priority: "low"
      optimization: "temporal_search"
      ttl_seconds: 60

# Layer 3: GitHub Workflow Integration
layer_3_github_integration:
  enabled: true
  module: "systems.integration.dpibs_github_integration"
  class: "DPIBSGitHubIntegrator"
  
  configuration:
    hook_timeout_ms: 50
    max_concurrent_operations: 5
    
    supported_events:
      - issue_created
      - issue_updated
      - issue_closed
      - pr_created
      - pr_updated
      - pr_merged
      - comment_created
      - label_added
      - state_changed
    
    enhancement_strategies:
      - context_extraction
      - specification_analysis
      - benchmark_triggering
      - agent_notification
  
  event_agent_mapping:
    issue_created: ["rif-analyst"]
    issue_updated: ["rif-analyst", "rif-implementer"]
    "state:analyzing": ["rif-analyst"]
    "state:planning": ["rif-planner"] 
    "state:architecting": ["rif-architect"]
    "state:implementing": ["rif-implementer"]
    "state:validating": ["rif-validator"]
    "state:learning": ["rif-learner"]
    pr_created: ["rif-pr-manager"]
    pr_updated: ["rif-pr-manager"]
    pr_merged: ["rif-learner"]
  
  # Extended Claude hooks for GitHub integration
  enhanced_hooks:
    GitHubIssueCreated:
      - type: "python"
        module: "systems.integration.dpibs_github_integration"
        function: "process_issue_created_event"
        output: "context"
        description: "DPIBS enhancement for issue creation"
    GitHubStateChange:
      - type: "python"
        module: "systems.integration.dpibs_github_integration"
        function: "process_state_change_event"
        output: "context"
        description: "DPIBS enhancement for workflow state changes"
    GitHubPRCreated:
      - type: "python"
        module: "systems.integration.dpibs_github_integration"
        function: "process_pr_created_event"
        output: "context"
        description: "DPIBS enhancement for PR creation"

# Layer 4: RIF State Machine Integration
layer_4_state_machine_integration:
  enabled: true
  module: "systems.integration.dpibs_state_machine_integration"
  class: "DPIBSStateMachineIntegrator"
  
  configuration:
    transition_timeout_ms: 500
    max_concurrent_transitions: 3
    context_optimization_enabled: true
    benchmarking_integration_enabled: true
    learning_integration_enabled: true
  
  # State machine integration (preserves existing workflow)
  workflow_states:
    new:
      agents: []
      timeout: "30m"
    analyzing:
      agents: ["rif-analyst"]
      timeout: "1h"
    planning:
      agents: ["rif-planner"]
      timeout: "1h"
    architecting:
      agents: ["rif-architect"]
      timeout: "2h"
    implementing:
      agents: ["rif-implementer"]
      timeout: "4h"
      checkpoints: true
    validating:
      agents: ["rif-validator"]
      timeout: "2h"
    learning:
      agents: ["rif-learner"]
      timeout: "30m"
    complete:
      agents: ["rif-learner"]
      final: true
  
  # DPIBS enhancements by state
  state_enhancements:
    analyzing:
      context_optimization: true
      pattern_recognition: true
      complexity_assessment: true
    planning:
      workflow_optimization: true
      checkpoint_planning: true
    architecting:
      system_design_patterns: true
      integration_analysis: true
    implementing:
      context_delivery: true
      checkpoint_tracking: true
    validating:
      benchmarking_analysis: true
      evidence_collection: true
      quality_gates: true
    learning:
      knowledge_updates: true
      pattern_extraction: true
      metrics_analysis: true

# Layer 5: Backward Compatibility Layer
layer_5_compatibility:
  enabled: true
  module: "systems.integration.dpibs_compatibility_layer"
  class: "DPIBSCompatibilityLayer"
  
  configuration:
    fallback_timeout_ms: 1000
    compatibility_check_interval: 300
    migration_support_enabled: true
    gradual_adoption_enabled: true
    automatic_fallback_enabled: true
  
  # Backward compatibility requirements (BCR1, BCR2, BCR3)
  compatibility_requirements:
    BCR1_existing_functionality:
      description: "All existing RIF agent workflows continue to function without modification"
      critical: true
      test: "agent_workflow_compatibility"
      fallback: "use_existing_agent_system"
    BCR2_gradual_adoption:
      description: "DPIBS features can be enabled incrementally without disrupting existing workflows"
      critical: true
      test: "gradual_adoption_compatibility"
      fallback: "selective_feature_disable"
    BCR3_data_compatibility:
      description: "Existing knowledge database data remains accessible and functional"
      critical: true
      test: "knowledge_database_compatibility"
      fallback: "use_existing_database"
  
  # Feature compatibility matrix
  feature_compatibility:
    agent_context_enhancement:
      level: "full_backward_compatible"
      fallback: "use_existing_agent_system"
      migration_required: false
    mcp_knowledge_optimization:
      level: "gradual_adoption"
      fallback: "use_existing_mcp_server"
      migration_required: false
    github_workflow_enhancement:
      level: "full_backward_compatible"
      fallback: "use_existing_hooks"
      migration_required: false
    state_machine_integration:
      level: "full_backward_compatible"
      fallback: "use_existing_workflow"
      migration_required: false
    benchmarking_analysis:
      level: "gradual_adoption"
      fallback: "skip_benchmarking"
      migration_required: false

# Integration Orchestration
orchestration:
  # Initialization order (critical for dependencies)
  initialization_order:
    1: "layer_5_compatibility"      # Must be first for fallback mechanisms
    2: "layer_1_agent_integration"  # Foundation layer
    3: "layer_2_mcp_integration"    # Knowledge layer  
    4: "layer_3_github_integration" # Workflow triggers
    5: "layer_4_state_machine_integration"  # Top-level orchestration
  
  # Health monitoring
  health_monitoring:
    enabled: true
    check_interval_seconds: 60
    failure_threshold: 3
    recovery_enabled: true
    
    critical_components:
      - "layer_1_agent_integration"
      - "layer_5_compatibility"
    
    performance_monitoring:
      - "response_times"
      - "cache_hit_rates"
      - "error_rates"
      - "throughput"
  
  # Failure handling
  failure_handling:
    strategy: "graceful_degradation"
    max_retries: 3
    backoff_multiplier: 2
    circuit_breaker_enabled: true
    fallback_to_existing_functionality: true

# Integration Validation
validation:
  # Integration testing framework
  test_suites:
    unit_tests:
      - "test_agent_context_integration"
      - "test_mcp_optimization"
      - "test_github_integration"
      - "test_state_machine_integration"
      - "test_compatibility_layer"
    
    integration_tests:
      - "test_end_to_end_workflow"
      - "test_backward_compatibility"
      - "test_performance_targets"
      - "test_fallback_mechanisms"
      - "test_gradual_adoption"
    
    performance_tests:
      - "test_response_time_targets"
      - "test_cache_performance"
      - "test_concurrent_operations"
      - "test_system_overhead"
  
  # Success criteria
  success_criteria:
    all_layers_functional: true
    performance_targets_met: true
    backward_compatibility_verified: true
    zero_regression_confirmed: true
    gradual_adoption_working: true

# Deployment Configuration
deployment:
  strategy: "blue_green"
  rollback_enabled: true
  monitoring_enabled: true
  
  phases:
    1:
      name: "Compatibility Verification"
      components: ["layer_5_compatibility"]
      success_criteria: ["all_compatibility_tests_pass"]
    2:
      name: "Foundation Layer"
      components: ["layer_1_agent_integration"]
      success_criteria: ["agent_context_enhancement_working"]
    3:
      name: "Knowledge Enhancement"
      components: ["layer_2_mcp_integration"]
      success_criteria: ["mcp_optimization_working"]
    4:
      name: "Workflow Integration"
      components: ["layer_3_github_integration", "layer_4_state_machine_integration"]
      success_criteria: ["github_integration_working", "state_machine_working"]
    5:
      name: "Full Integration"
      components: ["all_layers"]
      success_criteria: ["end_to_end_integration_working"]

# Documentation and Support
documentation:
  architecture_guide: "docs/dpibs-integration-architecture.md"
  api_documentation: "docs/dpibs-integration-api.md"
  troubleshooting_guide: "docs/dpibs-integration-troubleshooting.md"
  migration_guide: "docs/dpibs-integration-migration.md"
  
support:
  logging_level: "INFO"
  metrics_collection: true
  debug_mode: false
  support_email: "rif-support@example.com"

# Version and Metadata
metadata:
  created_date: "2025-08-24"
  created_by: "RIF-Implementer"
  issue_reference: "#121"
  architecture_phase: "Phase 3"
  implementation_status: "Complete"
  last_updated: "2025-08-24T00:00:00Z"