# RIF Emergency Hotfix Configuration
# Implements sub-30-minute resolution capability

# Branch Configuration
production_branch: "production"  # Branch to create hotfixes from
main_branch: "main"              # Branch for backports
development_branch: "develop"     # Optional development branch

# Review Requirements (Emergency Reduced)
reviewer_count: 1                # Reduced from standard 2
auto_merge_on_approval: true     # Emergency auto-merge
require_owner_review: false      # Bypass owner requirement

# Time Constraints
timeout_minutes: 30              # Total resolution SLA
deployment_timeout: 10           # Maximum deployment time
rollback_timeout: 5              # Maximum rollback time

# Required Labels
required_labels:
  - "hotfix"
  - "emergency"
  - "priority:critical"

# Optional Labels (Applied Automatically)
auto_labels:
  - "skip-changelog"
  - "expedited-review"
  - "production-deployment"

# Quality Gates (Minimal for Emergency)
quality_gates:
  # Critical Checks (Always Required)
  security_scan: true
  smoke_tests: true
  basic_syntax_check: true
  
  # Standard Checks (Skipped in Emergency)
  full_test_suite: false
  integration_tests: false
  performance_benchmarks: false
  documentation_check: false
  code_coverage_check: false
  dependency_audit: false
  
  # Emergency-Specific Checks
  rollback_verification: true
  deployment_health_check: true

# Deployment Configuration
deployment:
  strategy: "blue_green"          # or "rolling", "recreate"
  health_check_path: "/health"
  health_check_timeout: 30
  verification_tests:
    - "curl -f $DEPLOYMENT_URL/health"
    - "curl -f $DEPLOYMENT_URL/api/status"
  
  # Rollback Configuration
  automatic_rollback: true
  rollback_triggers:
    - "health_check_failure"
    - "error_rate_spike"
    - "deployment_timeout"

# Notification Configuration
notifications:
  # Slack Integration
  slack:
    webhook_url: null  # Set via environment: SLACK_WEBHOOK_URL
    channels:
      - "#emergency-alerts"
      - "#production-deployments"
    mention_groups:
      - "@on-call"
      - "@platform-team"
  
  # Email Notifications
  email:
    smtp_server: null  # Configure if needed
    emergency_list:
      - "on-call@company.com"
      - "platform-team@company.com"
  
  # PagerDuty Integration
  pagerduty:
    api_key: null      # Set via environment: PAGERDUTY_API_KEY
    service_id: null   # Your PagerDuty service ID
    escalation_policy: "emergency-hotfix"

# Incident Management
incident_tracking:
  # Incident ID Format
  id_format: "INC-{date}-{time}"  # e.g., INC-20250825-143022
  
  # Severity Levels
  severity_levels:
    critical: 
      sla_minutes: 15
      auto_escalate: true
      require_post_mortem: true
    high:
      sla_minutes: 30
      auto_escalate: false
      require_post_mortem: true
    medium:
      sla_minutes: 60
      auto_escalate: false
      require_post_mortem: false
  
  # Post-Mortem Configuration
  post_mortem:
    auto_generate: true
    template_path: "templates/post-mortem.md"
    required_sections:
      - "timeline"
      - "root_cause"
      - "impact_assessment"
      - "action_items"
    
    # Auto-assign post-mortem review
    assignees:
      - "incident-commander"
      - "engineering-manager"

# Monitoring and Alerting
monitoring:
  # Metrics to Track
  metrics:
    - "deployment_duration"
    - "time_to_resolution"
    - "rollback_frequency"
    - "success_rate"
  
  # Alert Thresholds
  thresholds:
    deployment_duration_max: 600  # 10 minutes
    time_to_resolution_max: 1800  # 30 minutes
    error_rate_spike: 0.05        # 5%
    response_time_spike: 2.0      # 2x normal
  
  # Health Check Configuration
  health_checks:
    interval_seconds: 30
    failure_threshold: 3
    success_threshold: 2

# Security Configuration
security:
  # Emergency Access Control
  emergency_access:
    enabled: true
    max_duration_minutes: 60
    audit_trail: true
    require_justification: true
  
  # Bypass Controls (Emergency Only)
  bypass_controls:
    code_review: true      # Allow single reviewer
    branch_protection: true # Allow direct push in emergency
    status_checks: false   # Never bypass security checks
  
  # Audit Requirements
  audit:
    log_all_actions: true
    retain_logs_days: 90
    compliance_checks: true

# Testing and Validation
testing:
  # Pre-deployment Tests (Minimal)
  pre_deployment:
    - "syntax_check"
    - "security_scan"
    - "smoke_tests"
  
  # Post-deployment Validation
  post_deployment:
    - "health_check"
    - "basic_functionality"
    - "error_rate_monitoring"
  
  # Simulation Tests
  simulation:
    scenarios:
      - "database_connection"
      - "authentication_bypass"
      - "memory_leak"
      - "api_timeout"
      - "configuration_error"

# Integration Points
integrations:
  # GitHub Actions
  github_actions:
    workflow_file: ".github/workflows/emergency-hotfix.yml"
    required_secrets:
      - "GITHUB_TOKEN"
      - "SLACK_WEBHOOK_URL"
      - "PAGERDUTY_API_KEY"
  
  # Deployment Tools
  deployment_tools:
    kubernetes: true
    docker: true
    serverless: false
    traditional: false
  
  # Monitoring Tools
  monitoring_tools:
    datadog: false
    newrelic: false
    prometheus: false
    custom: true

# Compliance and Governance
compliance:
  # Regulatory Requirements
  sox_compliance: true
  gdpr_compliance: true
  hipaa_compliance: false
  
  # Change Management
  change_advisory_board:
    bypass_emergency: true
    post_emergency_review: true
    notification_required: true
  
  # Documentation Requirements
  documentation:
    emergency_runbook: "docs/emergency-procedures.md"
    escalation_matrix: "docs/escalation-matrix.md"
    contact_list: "docs/emergency-contacts.md"

# Performance Targets
performance_targets:
  # Emergency Response SLAs
  incident_detection: 60       # seconds
  hotfix_creation: 300        # 5 minutes
  code_review: 600            # 10 minutes
  deployment: 600             # 10 minutes
  verification: 300           # 5 minutes
  total_resolution: 1800      # 30 minutes
  
  # Quality Metrics
  success_rate_target: 95     # %
  rollback_rate_max: 10       # %
  false_alarm_rate_max: 5     # %